sudo: required
services:
  - docker

before_install:
  - docker build -t zainsayed/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true zainsayed/docker-react npm run test -- --coverage

language: generic 

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-896967220871"
  bucket_path: "docker-react"
  on:
    branch: master

